# look at
#  https://eslint.org/docs/rules/
#  https://github.com/eslint/eslint/blob/master/packages/eslint-config-eslint/default.yml
#  https://github.com/adametry/gulp-eslint/blob/master/.eslintrc.yml
#  https://scionofbytes.me/code-craftsmanship/my-es-lint-and-why
env:
  es2020: true
  node: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
plugins:
  - jsdoc
  - import
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  ## jsdoc plugin
  jsdoc/require-returns-type: error
  jsdoc/valid-types: error

  ## overrides
  no-constant-condition: warn
  ## best practices
  array-callback-return: error
  arrow-spacing: error
  block-scoped-var: error
  complexity: error
  consistent-return: error
  curly: error
  default-case: error
  dot-notation: error
  guard-for-in: error
  eqeqeq: error
  indent: [warn, tab, { SwitchCase: 1 }]
  keyword-spacing: [error, { overrides: { function: { after: true } } }]
  max-classes-per-file: [error, 2]
  no-alert: error
  no-caller: error
  no-console: warn
  no-div-regex: error
  #  no-else-return: error
  no-empty: warn
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  #  no-magic-numbers: error
  no-multi-spaces: [error, ignoreEOLComments: true]
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-octal-escape: error
  no-param-reassign: error
  no-proto: error
  no-return-assign: error
  #  no-return-await: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  # no-unused-vars: [warn, {argsIgnorePattern: '^_', vars: all, varsIgnorePattern: '^_', caughtErrors: all}]
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    [
      warn,
      {
        argsIgnorePattern: '^_',
        vars: all,
        varsIgnorePattern: '^_',
        caughtErrors: all,
      },
    ]
  no-useless-call: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  #  no-warning-comments: warn
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  require-unicode-regexp: error
  wrap-iife: error
  yoda: error
  quotes: [warn, single, avoid-escape]
  strict: error

  ## Varibles:
  no-label-var: error
  #  no-shadow: error - used @typescript-eslint/no-shadow to avoid problems with enums
  no-undef-init: error
  #  no-undefined: error
  no-use-before-define: ['error', { 'functions': false }]

  ## node.js:
  callback-return: error
  global-require: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-sync: error

  ##Stylistic Issues
  array-bracket-spacing: [error, never, { singleValue: true }]
  block-spacing: error
  brace-style: [error, 1tbs, { allowSingleLine: true }]
  camelcase: error
  #  comma-dangle: [error] # nm!
  #  comma-dangle: [warn, always-multiline]
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: error
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names: [error, as-needed]
  func-style: [error, declaration, { allowArrowFunctions: true }]
  function-paren-newline: [error, consistent]
  key-spacing: error
  lines-between-class-members: [error, always, { exceptAfterSingleLine: true }]
  new-cap: [error, { capIsNew: false }]
  new-parens: error
  newline-per-chained-call: [error, { ignoreChainWithDepth: 3 }]
  no-array-constructor: error
  no-bitwise: error
  #  no-inline-comments: error
  no-lonely-if: error
  no-mixed-operators: [error, { 'groups': [['&&', '||']] }]
  no-multiple-empty-lines: [error, { max: 1, maxBOF: 0, maxEOF: 0 }]
  no-negated-condition: error
  no-new-object: error
  no-restricted-imports: ['error', { 'patterns': ['../*'] }]
  no-trailing-spaces: error
  #  no-underscore-dangle: [error, { allow: [_id], allowAfterThis: true, enforceInMethodNames: true }]
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  object-curly-newline: error
  object-curly-spacing: [error, always]
  one-var: [error, never]
  operator-assignment: error
  operator-linebreak: error
  padded-blocks: [error, never]
  padding-line-between-statements:
    - error
    - { blankLine: never, prev: block-like, next: return }
    - { blankLine: always, prev: directive, next: '*' }
    - { blankLine: never, prev: directive, next: directive }
  prefer-object-spread: error
  quote-props: [error, as-needed]

  semi: [error, always]
  semi-spacing: error
  semi-style: error
  space-before-blocks: error
  space-before-function-paren:
    [error, { anonymous: always, asyncArrow: always, named: never }]
  switch-colon-spacing: error
  spaced-comment: error
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  template-tag-spacing: error
  unicode-bom: warn

  ## ECMAScript 6
  arrow-parens: [error, as-needed, { requireForBlockBody: true }]
  generator-star-spacing: error
  no-confusing-arrow: [error, { allowParens: true }]
  no-duplicate-imports: error
  no-useless-computed-key: error
  #no-useless-constructor: warn
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: error
  sort-imports: [error, { allowSeparatedGroups: true, ignoreCase: true }]
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error

  ## @typescript-eslint
  '@typescript-eslint/no-this-alias':
    [error, { allowDestructuring: true, allowedNames: ['that'] }]
  '@typescript-eslint/no-extra-semi': error
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/member-delimiter-style': error
  '@typescript-eslint/no-useless-constructor': warn
  'import/no-default-export': error
  "@typescript-eslint/no-explicit-any": error
